// // import { Poppins, Fira_Sans } from "next/font/google";
// import "../globals.css";
// // import Nav from "./(common)/commponents/global/Nav";
// import Footer from "../(common)/commponents/global/Footer";
// import Nav from "../(common)/commponents/global/Nav";



// // const poppins = Poppins({
// //   variable: "--headingFont",
// //   subsets: ["latin"],
// //   display: 'swap',
// //   weight: ['400', '500', '600', '700', '800'],
// //   // variable: '--font-poppins',
// // });

// // const firaSans = Fira_Sans({
// //   variable: "--textFont",
// //   subsets: ["latin"],
// //   display: 'swap',
// //   weight: ['300', '400', '500', '600'],
// //   // variable: '--font-fira-sans',
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };
// // app/layout.js
// export const metadata = {
//   title: {
//     default: "SEAP | Clean Energy for Every Community",
//     template: "%s | SEAP",
//   },
//   description:
//     "Sustainable Energy Access Project (SEAP) delivers clean, affordable energy and digital access across Nigeria.",
//   metadataBase: new URL("https://seap.com.ng"),
//   openGraph: {
//     type: "website",
//     siteName: "seap",
//   },
//   twitter: {
//     card: "summary_large_image",
//   },
//   robots: {
//     index: true,
//     follow: true,
//   },
  
// };


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="light" >
//       <body
//         // className={`${poppins.variable} ${firaSans.variable} antialiased`}
//       >
//         <Nav/>
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   );
// }


import Nav from "../(common)/commponents/global/Nav";
import Footer from "../(common)/commponents/global/Footer";

export default function SiteLayout({ children }) {
  return (
    <>
      <Nav />
      {children}
      <Footer />
    </>
  );
}